aa2g/AA2Unlimited

AAUnlimitedExe/PathInfo.cpp

> `//all hail copy n paste`
I beg to differ ;)
The replicated code for `g_AAEditPath` added a `'\0'` instead of a backslash as supposed:
```C++
if (buffer[outSize - 2] != '\\') {
buffer[outSize - 1] = '\0';
buffer[outSize] = '\0';
}
g_AAEditPath = std::string((char*)buffer);
```
I have refactored the duplicated parts into their own functions and added a few comments

AA2Edit path wasn't properly terminated by "\\" due to a copy-paste bug

---

AAUnlimited/Functions/Shared/Shadowing.cpp

More modular shadowing.
Under the data\sets folder you can group shadow files in folders. Only folders with names that start with "!" will be considered for shadowing.

Add shadow sets under data\sets. Enabled sets start with !, disabled without

---

AAUnlimited/Functions/Shared/Shadowing.cpp

This pull request fixes a failure to check more than one shadow set folder.

Shadow Set Fix

---

AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/Shared/Triggers/Actions.cpp
AAUnlimited/Functions/Shared/Triggers/Thread.h

NOTE: triggers log level is INFO. SPAM is too spammy and is useless. Letting user pick whatever level they want is also bad. Therefore just limited it to INFO.

Triggers logging

---

AAUnlimited/External/ExternalClasses/CharacterRelation.h
AAUnlimited/External/ExternalClasses/CharacterStatus.h
AAUnlimited/External/ExternalClasses/CharacterStruct.h
AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/Shared/Slider.cpp
AAUnlimited/Functions/Shared/Triggers/Actions.cpp
AAUnlimited/Functions/Shared/Triggers/Event.h
AAUnlimited/Functions/Shared/Triggers/Expressions.cpp
AAUnlimited/Functions/Shared/Triggers/Thread.cpp
AAUnlimited/Functions/Shared/Triggers/Thread.h
AAUnlimited/MemMods/AAPlay/Events/NpcActions.cpp

a couple fixes/additions:
* Triggers have action cap raised from 1000 to INT_MAX
* Added cumstats and risky days setters
* Added legs influence to hip height slider
* Changed workflow of npc response

Triggers: cumstats setters and removed action limit

---

AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/AAUCardData.h
AAUnlimited/Functions/Shared/Slider.cpp

New sliders:
Neck Height Slider.
Breast Pushup Slider.
Nipple Slider.
Upper Arm size Slider. (split from arm size slider.)
Under Arm size Slider. (split from arm size slider.)
Butt Size Slider (Split from Hip Size slider, essentially the same thing - X axis scaling.)
Upper Thigh Width. (split from Thigh Thickness 1)
Upper Thigh Thickness. (split from Thigh Thickness 1)
Lower Thigh Width. (split from Thigh Thickness 2) 
Lower Thigh Thickness. (split from Thigh Thickness 2)
Calves Width. (split from Calves Thickness)
Calves Thickness. (split from Calves Thickness)

More sliders

---

AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/Shared/Slider.cpp

Made this commit as simple as possible. Hopefully i didn't mess anything up.

Tot Sliders For Tot Face Bones!

---

AAUnlimited/External/ExternalClasses/TimeData.h
AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/CharInstData.h
AAUnlimited/Functions/Shared/Overrides.cpp
AAUnlimited/Functions/Shared/Slider.cpp
AAUnlimited/Functions/Shared/Triggers/Expressions.cpp
AAUnlimited/Texts/init.lua

Onemoretotslider

---

AAUnlimited/Texts/init.lua

New version number

---

AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/Shared/Slider.cpp

Fully tested now, hopefully i did not forget anything.
BalloonTits: Universal breast scaling.
Breast Distance: Base breast frame X axis translation.
Breast Perkiness: Areolae frame Z axis scaling.

Breast sliders

---

AAUnlimited/Functions/AAPlay/Subs.cpp
AAUnlimited/Functions/AAPlay/Subs.h
AAUnlimited/Functions/RenderWrap.cpp
AAUnlimited/Script/ScriptLua.cpp
AAUnlimited/Texts/config.lua
AAUnlimited/Texts/mod/subtitles.lua

Advanced settings for:
- Font size, family, different colors for female and male character.
- Count and show duration of Subs lines.
- Outline size, color, opacity.
- Text position and alignment on the screen.

AA2 Subtitles v1.0.0

---

AAUnlimited/Functions/Shared/Slider.cpp

This reduces the effect the sliders have on the back. The effect on the hip slider is reduced since the hip correction slider exists.

Add a small translation to thickness sliders so that the back doesn't become too thick

---

AAUnlimited/Functions/Shared/Triggers/Triggers.cpp

Fixed a trigger logic error. It used to not clear the ITE state in cases where an  'If' came after an 'ElseIf'. This made the game think the ElseIf chain was not resolved.

Fixed a trigger logic error. 

---

AAUnlimited/Functions/RenderWrap.cpp
AAUnlimited/General/DrawD3D.cpp
AAUnlimited/General/DrawD3D.h
AAUnlimited/MemMods/AAPlay/Events/ScreenCapture.cpp
AAUnlimited/StdAfx.h

- Added HUD system (framework) for drawing text and basic shapes.
- Added custom Cursor, thats is shown over HUD, when it's real need.
- GDI init now starting with the init of the game graphics.

DrawD3D (HUD framework)

---

AAUnlimited/AAUnlimited.vcxproj
AAUnlimited/AAUnlimited.vcxproj.filters
AAUnlimited/Functions/AAPlay/Subs.cpp
AAUnlimited/Functions/Notifications.cpp
AAUnlimited/Functions/Notifications.h
AAUnlimited/Functions/RenderWrap.cpp
AAUnlimited/Functions/Shared/Triggers/Actions.cpp
AAUnlimited/Functions/Shared/Triggers/Thread.h
AAUnlimited/General/DrawD3D.cpp
AAUnlimited/General/Util.cpp
AAUnlimited/General/Util.h
AAUnlimited/MemMods/AAPlay/Events/ScreenCapture.cpp
AAUnlimited/Script/ScriptLua.cpp
AAUnlimited/StdAfx.h
AAUnlimited/Texts/config.lua
AAUnlimited/Texts/mod/notifications.lua

- Added Notifications system for ingame actions messages, etc.
- Added Notification about saved screenshot.
- Added 'Notification' action for Triggers (Modules system).

Notifications

---

AAUnlimited/General/Util.h
AAUnlimited/Script/ScriptLua.cpp
AAUnlimited/Texts/mod/notifications.lua
AAUnlimited/Texts/mod/subtitles.lua

- Verification for old Subs params from config.
- Some previous code cleaning.

Subs and Notifications position verification.

---

AAUnlimited/MemMods/AAPlay/Events/NpcActions.cpp
AAUnlimited/MemMods/AAPlay/Events/NpcActions.h
AAUnlimited/MemMods/Hook.cpp

https://www.youtube.com/watch?v=ZDiX9wwo670

Roster crash bandaid fix

---

AAUnlimited/MemMods/AAPlay/Events/NpcActions.cpp

changed the way offsets are defined

offset calculation

---

AAUnlimited/Texts/mod/music.lua
AAUnlimited/Texts/mod/musicconfig.lua

I made a mod that could be useful. It lets you change the current music at any time, prevent the music from being automatically changed, and overrides the H-scene music depending on the room entered.

Custom music mod

---

AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/AAEdit/UnlimitedDialog.h
AAUnlimited/MemMods/AAPlay/Events/ScreenCapture.cpp
AAUnlimited/Texts/mod/poser/dlg.lua
AAUnlimited/Texts/mod/poser/posemgr.lua

Very nice things

---

AAUnlimited/Texts/mod/triggers_supplemental.lua

then return end

---

AAUnlimited/Texts/mod/triggers_supplemental.lua

incorrect action name-id and missing action in the action namelist

---

AAUnlimited/Files/Config.h
AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp
AAUnlimited/Functions/AAPlay/GameState.cpp
AAUnlimited/Functions/AAPlay/GameState.h
AAUnlimited/Functions/AAPlay/HButtonMove.cpp
AAUnlimited/Functions/RenderWrap.cpp
AAUnlimited/Functions/Shared/Triggers/Actions.cpp
AAUnlimited/Functions/Shared/Triggers/Event.cpp
AAUnlimited/Functions/Shared/Triggers/Event.h
AAUnlimited/Functions/Shared/Triggers/Expressions.cpp
AAUnlimited/Functions/Shared/Triggers/Thread.h
AAUnlimited/MemMods/AAPlay/Events/Time.cpp
AAUnlimited/MemMods/Shared/Events/GameTick.cpp
AAUnlimited/StdAfx.h
AAUnlimited/Texts/mod/triggers_supplemental.lua

Delayed events and jmcp and whatnot

---

AAUnlimited/Functions/AAEdit/UnlimitedDialog.cpp

On the Body tab the bone list dropdown menu is repopulated every time the tab is accessed. This change makes the menu be repopulated only when it's accessed and only filled with relevant bones from the selected XX file.

Populate frame list only for the selected XX file
